[package]
name = "aoc2020"
version = "0.1.0"
authors = ["smmalis37@gmail.com"]
edition = "2018"

[dependencies]
paste = "1"
criterion = "0.3"
serde_scan = "0.4.1"
bytecount = "0.6"
derive_builder = "0.9"
bstr_parse = "0.1"
